export default [
  { title: "L'Étranger", author: "Albert Camus" },
  { title: "La Peste", author: "Albert Camus" },
  { title: "Le Mythe de Sisyphe", author: "Albert Camus" },
  { title: "La Chute", author: "Albert Camus" },
  { title: "2084 : La Fin du monde", author: "Boualem Sansal" },
  { title: "Le Village de l'Allemand ou le Journal des frères Schiller", author: "Boualem Sansal" },
  { title: "Gouverner au nom d'Allah", author: "Boualem Sansal" },
  { title: "L'Attentat", author: "Yasmina Khadra" },
  { title: "Les Hirondelles de Kaboul", author: "Yasmina Khadra" },
  { title: "Les Sirènes de Bagdad", author: "Yasmina Khadra" },
  { title: "Nedjma", author: "Kateb Yacine" },
  { title: "Le Polygone étoilé", author: "Kateb Yacine" },
  { title: "L'Amour, la Fantasia", author: "Assia Djebar" },
  { title: "Les Enfants du Nouveau Monde", author: "Assia Djebar" },
  { title: "Fantasia : Une Cavalcade algérienne", author: "Assia Djebar" },
  { title: "Le Dernier Été de la raison", author: "Tahar Djaout" },
  { title: "Les Vigiles", author: "Tahar Djaout" },
  { title: "Le Fils du pauvre", author: "Mouloud Feraoun" },
  { title: "La Terre et le Sang", author: "Mouloud Feraoun" },
  { title: "Mémoires de la chair", author: "Ahlam Mosteghanemi" },
  { title: "Le Chaos des sens", author: "Ahlam Mosteghanemi" },
  { title: "La Répudiation", author: "Rachid Boudjedra" },
  { title: "Topographie idéale pour une agression caractérisée", author: "Rachid Boudjedra" },
  { title: "La Vie sexuelle d'un Islamiste à Paris", author: "Leïla Marouane" },
  { title: "L'Homme que j'aimais", author: "Leïla Marouane" }
];
